name: Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
    uses: actions/setup-python@v3
    with:
      python-version: "3.10"

      - name: Install
      with:
        token: ${{ secrets.ANTPACK_PRIVATE_CLONE }}
        submodules: true
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r test_requirements.txt

      - name: Test and Coverage
      run: python -m pytest --cov --cov-report json

      - name: Update Coverage Badge
      # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: we-cli/coverage-badge-action@main
