name: test

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ANTPACK_PRIVATE_CLONE }}
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip numpy nanobind pytest
        pip install -r test_requirements.txt
        pip install . --verbose
    - name: Test with pytest
      run: |
        pytest tests --cov --cov-report json

      - name: Update Coverage Badge
      # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: we-cli/coverage-badge-action@main
