name: test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Python setup
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ANTPACK_PRIVATE_CLONE }}
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        git submodule update --remote --recursive
        python -m pip install --upgrade pip numpy nanobind pytest pytest-cov
        pip install -r test_requirements.txt
        pip install -e . --verbose

    - name: Test with pytest
      run: |
        pytest tests --cov --cov-report json
